version: '3.9'
services:
  backend:
    image: fastify-api
    ports:
      - '50021:50021'
  postgres:
    restart: always
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=rs_dev
      - POSTGRES_PASSWORD=2000
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    driver: local
